apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coinupfront
spec:
  rules:
    - host: coinupfront.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coinupfront
                port:
                  number: 80
